# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mapping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicyearClassRelationClassId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicyearclassrelation_id', models.IntegerField(blank=True, null=True)),
                ('classdetails_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'academicyear_class_relation_class_id',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassSectionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'class_section_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassSectionMappingSectionName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classsectionmapping_id', models.IntegerField(blank=True, null=True)),
                ('sections_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'class_section_mapping_section_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassSubjectMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'class_subject_mapping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassSubjectMappingSubjectName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classsubjectmapping_id', models.IntegerField(blank=True, null=True)),
                ('subject_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'class_subject_mapping_subject_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleUserRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'role_user_relation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoleUserRelationUserName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleuserrelation_id', models.IntegerField(blank=True, null=True)),
                ('staffdetails_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'role_user_relation_user_name',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherSubjectRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'teacher_subject_relation',
                'managed': False,
            },
        ),
    ]
